### ISSUE TITLE
[FEATURE REQUEST] Quick switch between Expanded Radar ON and OFF

### ISSUE THREAD

**Issue by cCaptainn** [YimMenu-Lua/Harmless-Scripts#1]
### What should the Lua script be called?

Expanded Radar ON/OFF

### Describe the suggestion

A toggle switch or checkbox which would quickly toggle the Expanded Map option preset in Setting>Display of GTAV/GTAO.

### Why do you think this Lua script would be useful?

I know I switch between the two often, as do others I play with. Obviously we could use the playerlist key to temporarily expand the map instead, but I prefer to not need to tap that button over and over while driving around as it interrupts the flow of gameplay

### List options in Lua script

Expanded Radar [On]
Expanded Radar [Off]

### Existing script

- [X] I've confirmed that this script DOES NOT already exist.

**Comment by Harmless05** [comment]
I'll see what I can do, but I can’t say when it will be ready or added because I'm currently quite busy.

**Comment by cCaptainn** [comment]
Thanks! I just wanted to drop the idea, so if it ever shows up I'll be happy!

**Comment by Harmless05** [comment]
It's possible, but it appears that the native used to expand the map is broken or isn't working as intended. I also tested radar/minimap zoom and that works just fine.

**Comment by lonelybud** [comment]
> It's possible, but it appears that the native used to expand the map is broken or isn't working as intended. I also tested radar/minimap zoom and that works just fine.

		`HUD::DISPLAY_RADAR(HUD::IS_RADAR_HIDDEN());` ?

**Comment by cCaptainn** [comment]
That's SET_RADAR_ZOOM correct? It would be comparatively dirty but could that be used to achieve the same effect as the native option?

**Comment by Harmless05** [comment]
Yes, that's for the radar zoom effect. YimMenu also uses the "bigmap" aka expanded map in their orbital drone, but that part is broken as well in their script.

**Comment by Harmless05** [comment]
I've had more time to test the expanded map, and it seems to work perfectly in single player, it could be just online being weird. If you want a test build, let me know. I might include some other stuff in that build.

**Comment by Harmless05** [comment]
Added in the latest [release 1.2.0](https://github.com/YimMenu-Lua/Harmless-Scripts/releases/tag/v1.2.0)
