### ISSUE TITLE
[BUG] Update please

### ISSUE THREAD

**Issue by C47CH-71** [YimMenu-Lua/Harmless-Scripts#3]
### What feature does this affect

Nothing works

### Describe the bug

The script is loaded, but none of its menus are active; in fact, nothing works.

### How to replicate

I don't know what to write here...

### Expected Behavior

working version of the script for the new version YimMenu

### Possible evidence

![Screenshot 2024-05-03 133041](https://github.com/YimMenu-Lua/Harmless-Scripts/assets/162917432/94107fce-f48f-4c7a-990c-34146411e0ef)
![Screenshot 2024-05-03 133403](https://github.com/YimMenu-Lua/Harmless-Scripts/assets/162917432/64b848bf-667b-4e99-9edc-72208b8adda6)

### YimMenu logs

[cout.log](https://github.com/YimMenu-Lua/Harmless-Scripts/files/15199132/cout.log)

### Additional context

And overall, an excellent script, drift mode using Shift and health regeneration are just a must have.
thx

### Build

- [X] I've confirmed that the issue exists in the latest version of YimMenu.

### Harmlesse's Scripts version

- [X] I've confirmed that I am using the latest version of this script.

**Comment by Harmless05** [comment]
Latest version of this script (1.2.1) and YimMenu seems to be working for me with no errors. 
Please try deleting the script and the scripts config file `YimMenu -> scripts_config -> HSConfig.json` and download the latest version from here https://github.com/YimMenu-Lua/Harmless-Scripts/releases/tag/v1.2.1

**Comment by C47CH-71** [comment]
> Latest version of this script (1.2.1) and YimMenu seems to be working for me with no errors. Please try deleting the script and the scripts config file `YimMenu -> scripts_config -> HSConfig.json` and download the latest version from here https://github.com/YimMenu-Lua/Harmless-Scripts/releases/tag/v1.2.1

You are absolutely right, sorry for the trouble!! Thanks again for the wonderful functionality! To be honest, I’m a little shocked, because even abandoned the game for a couple of days...)
