### ISSUE TITLE
[BUG] game crashes when thermal vision is on

### ISSUE THREAD

**Issue by infinity-stack** [YimMenu-Lua/Harmless-Scripts#5]
### What feature does this affect

thermal vision crashes

### Describe the bug

it crashes you

### How to replicate

go to self options
press thermal vision

### Expected Behavior

thermal vision

### Build

- [X] I've confirmed that the issue exists in the latest version of YimMenu.

### Harmlesse's Scripts version

- [X] I've confirmed that I am using the latest version of this script.

**Comment by Harmless05** [comment]
I have not seen it crash yet, but when I have tried it in online then it just doesn't turn on (you can hear the vision toggle but will not show). This only seems to happen in online though and singleplayer wasn't affected.

Were you in singleplayer or online?
